### ISSUE TITLE
SMESH_Block.cpp:663: possible bad expression ?

### ISSUE THREAD

**Issue by dcb314** [tpaviot/smesh#20]
smesh-6.5.3.1/src/SMESH/SMESH_Block.cpp:662]: (style) Same expression on both sides of '&&'.

  bool hasHint = ( 0 <= theParamsHint.X() && theParamsHint.X() <= 1 &&
                   0 <= theParamsHint.Y() && theParamsHint.Y() <= 1 &&
                   0 <= theParamsHint.Y() && theParamsHint.Y() <= 1 );

Maybe

  bool hasHint = ( 0 <= theParamsHint.X() && theParamsHint.X() <= 1 &&
                   0 <= theParamsHint.Y() && theParamsHint.Y() <= 1 &&
                   0 <= theParamsHint.Z() && theParamsHint.Z() <= 1 );

**Comment by tpaviot** [comment]
Thanks @dcb314 for this insightful report. Fixed by commit 9d63738
