### ISSUE TITLE
‘myLastCreatedElems’ was not declared in this scope

### ISSUE THREAD

**Issue by tele1** [tpaviot/smesh#21]
I have problem with compile smesh on PCLinuxOS 32bit

log from compile in package
http://wklejto.pl/223009

log from compile hand
http://wklejto.pl/223011

I also please update instruction in README and this website,
How compile this software
I used like this:

mkdir build
cd build
LDFLAGS='-Wl,--as-needed'; export LDFLAGS
cmake ..
make

From packaging I have strange issue,
I need run like this:

cmake ..
cd ..
make

And I don't know why.

**Comment by tpaviot** [comment]
@tele1 There has been some changes, please test again with current master
