### ISSUE TITLE
SMESH_MeshEditor - compile problem [Solved]

### ISSUE THREAD

**Issue by tele1** [tpaviot/smesh#22]
I have problem with compile smesh in PCLinuxOS 32 bit

I have:
BuildRequires:  cmake
BuildRequires:  doxygen libgraphviz-devel
BuildRequires:  libopencascade-devel     0.17.0
BuildRequires:  libboost-devel
BuildRequires:  gcc-gfortran
BuildRequires:  f2c libf2c
BuildRequires:  dos2unix
BuildRequires:  libsm6
BuildRequires:  libx11-devel
BuildRequires:  libxext-devel
BuildRequires:  libmesaglu1-devel
BuildRequires:  freetype-devel
BuildRequires:  libfreeimage-devel

Errors:
http://wklejto.pl/223430

**Comment by pauloz1890** [comment]
I have the same issue...any way to get around this?

**Comment by tele1** [comment]
This is from my linux distribution
http://ftp.nluug.nl/pub/os/Linux/distr/pclinuxos/pclinuxos/srpms/SRPMS.pclos/smesh-6.5.3.1-1pclos2015.src.rpm

And unpack and check .spec file.
For you more important are :

```bash
BuildRequires:  cmake
BuildRequires:  doxygen
BuildRequires:  graphviz
BuildRequires:  opencascade
BuildRequires:  opencascade-devel
BuildRequires:  boost-devel
BuildRequires:  gcc-gfortran
BuildRequires:  f2c
BuildRequires:  f2c-devel
BuildRequires:  dos2unix

BuildRequires:  tbb-devel
BuildRequires:  libsm-devel
BuildRequires:  libx11-devel
BuildRequires:  libxext-devel
BuildRequires:  mesaglu-devel
BuildRequires:  freetype-devel
BuildRequires:  freeimage-devel
```
```
LDFLAGS='-Wl,--as-needed'; export LDFLAGS
%cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
       -DBoost_NO_BOOST_CMAKE=ON \
       -DMONOLITHIC_BUILD=OFF \
       ..

make
```
%cmake this is macro, however 
```bash
cmake 
```
also should work.
However if you will problem, from my linux distribution (PCLinuxOS)
this macro (%cmake) looks like this:

```bash
$ rpm --eval=%cmake

    
  CFLAGS="${CFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4}" ; export FFLAGS ; 
  LDFLAGS="$LDFLAGS -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id"; export LDFLAGS ; 
    mkdir -p build 
    cd build 
         
    /usr/bin/cmake .. \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
        -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib64 \
        -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DCMAKE_BUILD_TYPE=release \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DCMAKE_SKIP_RPATH:BOOL=ON \
         \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed  -Wl,-z,relro -Wl,-O1 -Wl,--build-id"
```

If you will have all dependencies, but something missing, maybe dependencies neeed compile with
some option, I don't  know.
You can check with which options are compiled PCLinuxOS dependencies
http://ftp.nluug.nl/pub/os/Linux/distr/pclinuxos/pclinuxos/srpms/SRPMS.pclos/
