### ISSUE TITLE
Errors with GCC 6 preview

### ISSUE THREAD

**Issue by hobbes1069** [tpaviot/smesh#26]
Fedora Rawhide had moved to GCC 6 preview for future Fedora 24 release and rebuilt all packages. smesh failed with the following error:

```
[ 66%] Building CXX object src/CMakeFiles/StdMeshers.dir/StdMeshers/StdMeshers_Arithmetic1D.cpp.o
cd /builddir/build/BUILD/smesh-6.5.3.1/build/src && /usr/bin/c++   -DCSFDB -DHAVE_CONFIG_H -DLIN -DOCC_CONVERT_SIGNALS -DStdMeshers_EXPORTS -D_OCC64 -I/builddir/build/BUILD/smesh-6.5.3.1 -I/builddir/build/BUILD/smesh-6.5.3.1/inc -I/usr/lib64/oce-0.16/../../include/oce  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -DNDEBUG -fPIC   -o CMakeFiles/StdMeshers.dir/StdMeshers/StdMeshers_Arithmetic1D.cpp.o -c /builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp
In file included from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_Mesh.hxx:37:0,
                 from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMESHDS_Mesh.hxx:31,
                 from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMESH_Mesh.hxx:34,
                 from /builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:30:
/builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_MeshInfo.hxx: In member function 'void SMDS_MeshInfo::Clear()':
/builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_MeshInfo.hxx:170:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 { for ( int i=0; i<myNb.size(); ++i ) if ( myNb[i] ) (*myNb[i])=0;
                  ~^~~~~~~~~~~~
In file included from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_Mesh.hxx:37:0,
                 from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMESHDS_Mesh.hxx:31,
                 from /builddir/build/BUILD/smesh-6.5.3.1/inc/SMESH_Mesh.hxx:34,
                 from /builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:30:
/builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_MeshInfo.hxx: In member function 'int SMDS_MeshInfo::NbElements(SMDSAbs_ElementType) const':
/builddir/build/BUILD/smesh-6.5.3.1/inc/SMDS_MeshInfo.hxx:240:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for ( int i=1+index( SMDSAbs_Node,1 ); i<myNb.size(); ++i ) if ( myNb[i] ) nb += *myNb[i];
                                            ~^~~~~~~~~~~~
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp: In member function 'virtual std::istream& StdMeshers_Arithmetic1D::LoadFrom(std::istream&)':
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:146:29: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in assignment
   isOK = (load >> _begLength);
                             ^
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:149:29: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in assignment
   isOK = (load >> _endLength);
                             ^
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:154:25: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in assignment
   isOK = (load >> intVal);
                         ^
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:157:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < _edgeIDs.capacity() && isOK; i++) {
                     ~~^~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:158:29: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in assignment
       isOK = (load >> intVal);
                             ^
/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Arithmetic1D.cpp:161:30: error: cannot convert 'std::basic_istream<char>' to 'bool' in assignment
     isOK = (load >> _objEntry);
                              ^
src/CMakeFiles/StdMeshers.dir/build.make:113: recipe for target 'src/CMakeFiles/StdMeshers.dir/StdMeshers/StdMeshers_Arithmetic1D.cpp.o' failed
make[2]: Leaving directory '/builddir/build/BUILD/smesh-6.5.3.1/build'
make[2]: *** [src/CMakeFiles/StdMeshers.dir/StdMeshers/StdMeshers_Arithmetic1D.cpp.o] Error 1
```

The full build log is here:
https://kojipkgs.fedoraproject.org//work/tasks/5028/12885028/build.log

**Comment by jf---** [comment]
@hobbes1069 , thanks for sharing this...
we **really** appreciate your commitment to the project, but given that GCC 6 is in beta, and that we deal with a code base that has been built up over ~2 decades, that new compiler targets will be supported over time, but I dont think you should expect a lot of time and effort being invested in making smesh compatible with GCC 6. 

AFAIK, the project hasnt been built with GCC 5 

Good to know that Fedora is moving to GCC 6, this is important information.

Many thanks for the heads up!

**Comment by hobbes1069** [comment]
Well that really puts me in difficult position as it's not practical to leave a package unbuilt in Rawhide indefinitely. The last good build was with GCC 5.3.1. 

Granted some of the purpose in building with GCC 6 is to work out the bugs now in Rawhide which is a development branch (not really even a release) but the N+1 Fedora release is always branched from it.

Most problems are not actually GCC 6 specific (I can speak to the specific errors with smesh) but in compiling with C++14 by default. Specifically, gnu++14 instead of gnu++98.

See https://gcc.gnu.org/gcc-6/changes.html

For now I'll try enforcing gnu++98.

**Comment by jf---** [comment]
@tpaviot , @hobbes1069 reported in #4 that things are building on GCC 6.0
thanks again for the heads up @hobbes1069

**Comment by hobbes1069** [comment]
I'm still enforcing gnu++98 for the time being but it would be nice to be able to remove that at some point.

**Comment by tpaviot** [comment]
@hobbes1069 your build log points to a broken link. Can you please use gist rather ?

**Comment by tpaviot** [comment]
@hobbes1069 Please test review/tp/gcc6-fixes

**Comment by hobbes1069** [comment]
Still ran into this:
`/builddir/build/BUILD/smesh-6.5.3.1/src/StdMeshers/StdMeshers_Deflection1D.cpp:121:30: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in initialization
   bool isOK = (load >> _value);
                              ^
`

**Comment by tpaviot** [comment]
@hobbes1069 Should be fixed by commit de2414bf4e5017ccc14afaad6f0e6efa832d0bf5 Please update your local copy and try again

**Comment by hobbes1069** [comment]
Ok, ran into another one in another file but I think I have enough examples now what to do. If I can find time tonight to work through them all successfully I'll provide a patch.

**Comment by hobbes1069** [comment]
I got tired of fixing them one by one and did a mass find/replace with all the "isOK = (load" lines and got a good build. I don't want to be redundant with your pull request so here's a link to the final patch, sorry I didn't do it separately from yours, should just be able to ignore the "already applied" hunks.

https://dl.dropboxusercontent.com/u/34775202/smesh-gcc6.patch

**Comment by tpaviot** [comment]
@hobbes1069 I applied your patch, rebased the gcc6-fixes branch on master. It should work, I create a pull request

**Comment by hobbes1069** [comment]
Are you planning a "patch/tweak" level release? Otherwise I'll just run with the patch for now.

**Comment by tpaviot** [comment]
@hobbes1069 Yes I plan to release recent works as soon as possible. Tell me if the compilation with gcc6 passes

**Comment by hobbes1069** [comment]
Yes, after finding and fixing all the cast issues the package built. There's a lot of warnings but we'll save that for another day :)

**Comment by tpaviot** [comment]
@hobbes1069 ok, please open another issue including gcc6 specific issues.
