### ISSUE TITLE
syncing with other smesh repositories

### ISSUE THREAD

**Issue by 5263** [tpaviot/smesh#3]
As you might have noticed, the FreeCAD maintainers keep their own copy of smesh.
Maybe we can try to merge our changes together.
https://github.com/FreeCAD/FreeCAD_sf_master/commits/master/src/3rdParty/salomesmesh
https://github.com/5263/FreeCAD/commits/historic-svn/src/3rdParty/salomesmesh

**Comment by tpaviot** [comment]
Done; Current smesh master contains fc fixes
