### ISSUE TITLE
pycalculix integration

### ISSUE THREAD

**Issue by jf---** [tpaviot/smesh#32]
[awesome & friendly OS FEM solver](https://github.com/spacether/pycalculix) 

mesh an part in pythonocc, solve in pycalculix

**Comment by tpaviot** [comment]
@jf--- Is this project still active ?

**Comment by jf---** [comment]
well, true that the last commit was a year ago. that said, calculix api is stable and calculix does promote the project on their site. i think its ok, and a easy to integrate project.

but true, this does fall in the category of amazing-if-you-have-the-time-to-delve-into-it

**Comment by tpaviot** [comment]
pycalculix is a dead project, closing the issue
