### ISSUE TITLE
MeshingParameters

### ISSUE THREAD

**Issue by trelau** [tpaviot/smesh#38]
Use of MeshingParameters instead of GlobalMeshingParameters gets the NETGENPlugin sources compiled. See here for a few commits:

https://github.com/trelau/smesh/commit/de6e4dac62dd7c77ca53aa45da53e334fe4980ed

**Comment by tpaviot** [comment]
@trelau ok, I think it's even possible to remove the ```#ifdef WNT``` statement and leave ```netgen::MeshingParameters& mparams = netgen::mparam;``` everywhere

There are still many unresolved links, but a few less than yesterday ...
