### ISSUE TITLE
build smesh 771 + netgen 6.2 successful

### ISSUE THREAD

**Issue by trelau** [tpaviot/smesh#39]
@tpaviot I was able to successfully build smesh 771 + netgen 6.2 after a few mods to both netgen and smesh.

For netgen, it required adding some "DLL_HEADER" flags to a number of classes and functions. Even for the netgen support branch, my guess is this is the place to start to resolve the unresolved externals. See commits here https://github.com/trelau/netgen/commits/master (the last two commits)

SMESH commits can be seen here https://github.com/trelau/smesh/commits/review/fc-smesh-771

I noticed a lot of changes to netgen_plugin to support netgen 6.2 from 4, and I figured it may be easier to use smesh 771 and update the pythonocc wrappers rather than modify old netgen_plugin code for netgen 6.2.

Can we move forward with smesh 771 + netgen 6.2 and update the pythonocc wrappers?

**Comment by tpaviot** [comment]
@yes that's what I noticed, I was about to push some changes to netgen-conda.

There are are actually many changes related to NetgenPlugin. But we have to go step by step. The first step is to get smesh compiled with netgen. With the current smesh671 it's almost done. Then update the pythonocc wrapper. The get pythonocc compile on all platforms. Then run tests. smesh771 is a lot heavier (vtk, hdf5 depenencies). I guess you can go your own wan with smesh771 when the process is completed with 671.
