### ISSUE TITLE
compatibility with OCCT 6.8.0 

### ISSUE THREAD

**Issue by 5263** [tpaviot/smesh#4]
We had to patch SMESH to use NCollection and stop linking against TKAdvTools
FreeCAD/FreeCAD_sf_master@1f162dec2d9999f169a065121e296849a4a8f6f1
FreeCAD/FreeCAD_sf_master@f7193ca6462e9604e999973183ac404d1c747a64
5263/FreeCAD@f675a7907dca3c9058847c4efadc85aa457d7c50

**Comment by hobbes1069** [comment]
Can someone update smesh here? I tried doing it myself but I'm not enough of a programmer and was not successful.

**Comment by jf---** [comment]
Thanks @5263 so much for the kind references! That's duly appreciated...

@hobbes1069 , yes, at some point...

**Comment by hobbes1069** [comment]
Ok, until it's fixed Fedora is stuck at OCE 0.15 and now 0.17.1 was released...

**Comment by jf---** [comment]
@5263 @hobbes1069 PR #27 to address this issue...

**Comment by hobbes1069** [comment]
Seemed to work well, I was able to build OCE 0.17 and smesh for Fedora Rawhide w/ gcc 6.

**Comment by jf---** [comment]
Woooohoooooo ;) 
Thanks for the update @hobbes1069

**Comment by jf---** [comment]
@tpaviot , PR merged, please close...
