### ISSUE TITLE
What to do with the NETGEN sources?

### ISSUE THREAD

**Issue by hobbes1069** [tpaviot/smesh#8]
We're currently not building the NETGEN Plugin library, I assume it needs to link against Netgen?

netgen 5.1 is on Fedora 20 so I could experiment with trying to get it to build...

If we want to use them I can add a find_library for netgen and enable the plugin build only if it's available.

**Comment by tpaviot** [comment]
@hobbes1069 wip see tp/netgen-support

**Comment by tpaviot** [comment]
@mblome stay tuned, netgen support is coming
